#!/bin/bash
echo "=== Terminal 1: Run this to start the chassis ==="
echo "sudo chmod 777 /dev/ttyS1"
echo "cd ~/ros2_ws"
echo "source /opt/ros/humble/setup.bash"
echo "source install/setup.bash"
echo "ros2 run ylhb_base base_controller"
echo ""
echo "=== Terminal 2: Run this to test moving ==="
echo "source /opt/ros/humble/setup.bash"
echo "ros2 topic pub --once /cmd_vel geometry_msgs/msg/Twist \"{linear: {x: 0.1}, angular: {z: 0.0}}\""
echo "ros2 run teleop_twist_keyboard teleop_twist_keyboard"
echo ""
echo "=== Terminal 3: Run this to check STM32 feedback ==="
echo "source /opt/ros/humble/setup.bash"
echo "ros2 topic echo /odom"
